import java.io.File;
import javax.swing.ImageIcon;

public class Home_Page_Frame extends javax.swing.JFrame {

    private waitUserAction waitUser;
    private static final long serialVersionUID = 4L;
    private String userName;
    public int operation;
    public String newProjName;
    public String showProjectName;
    
    public Home_Page_Frame(){
        initComponents();
    }
    public Home_Page_Frame(String username, waitUserAction wait) {
        this.userName = username;
        this.waitUser = wait;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        welcomeLabel.setText("Welcome to the WORTH service, "+this.userName);
        newProjectButton = new javax.swing.JButton();
        this.newProjectButton.setIcon(new ImageIcon("icone"+File.separator+"new.png"));
        listProjectsButton = new javax.swing.JButton();
        this.listProjectsButton.setIcon(new ImageIcon("icone"+File.separator+"listproject.png"));
        showProjectButton = new javax.swing.JButton();
        this.showProjectButton.setIcon(new ImageIcon("icone"+File.separator+"project.png"));
        newProjectName = new javax.swing.JTextField();
        showProjectLabel = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        this.logoutButton.setIcon(new ImageIcon("icone"+File.separator+"logout.png"));
        introLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        this.profileButton.setIcon(new ImageIcon("icone"+File.separator+"profile.png"));
        listAllUsersButton = new javax.swing.JButton();
        this.listAllUsersButton.setIcon(new ImageIcon("icone"+File.separator+"listusers.png"));
        listOnlineUsersButton = new javax.swing.JButton();
        this.listOnlineUsersButton.setIcon(new ImageIcon("icone"+File.separator+"onlineusers.png"));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ImageIcon img = new ImageIcon("icone"+File.separator+"logo.png");
        this.jLabel5.setIcon(img);
        newMembershipsButton = new javax.swing.JButton();
        this.newMembershipsButton.setIcon(new ImageIcon("icone"+File.separator+"newMem.png"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WORTH Home Page");

        welcomeLabel.setFont(new java.awt.Font("Ubuntu", 3, 20)); // NOI18N
        welcomeLabel.setToolTipText("Welcome to WORTH!");

        newProjectButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        newProjectButton.setText(" Create New Project");
        newProjectButton.setToolTipText("press to create a new worth project");
        newProjectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectButtonActionPerformed(evt);
            }
        });

        listProjectsButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        listProjectsButton.setText("List My Projects");
        listProjectsButton.setToolTipText("press to list all your projects");
        listProjectsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listProjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProjectsButtonActionPerformed(evt);
            }
        });

        showProjectButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        showProjectButton.setText(" Show Single Project Menu");
        showProjectButton.setToolTipText("press to open a project menu");
        showProjectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProjectButtonActionPerformed(evt);
            }
        });

        newProjectName.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        newProjectName.setToolTipText("insert the new project name");

        showProjectLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        showProjectLabel.setToolTipText("type the name of the project of which you want to open the menu");

        logoutButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        logoutButton.setText("Log out");
        logoutButton.setToolTipText("press to leave the WORTH system");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        introLabel.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        introLabel.setText("What project do you want to work on?");

        profileButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        profileButton.setText("Profile Settings");
        profileButton.setToolTipText("press to open your profile settings window");
        profileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        listAllUsersButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        listAllUsersButton.setText(" List WORTH Users");
        listAllUsersButton.setToolTipText("press to list all the users registered to WORTH");
        listAllUsersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listAllUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllUsersButtonActionPerformed(evt);
            }
        });

        listOnlineUsersButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        listOnlineUsersButton.setText(" List Online WORTH Users");
        listOnlineUsersButton.setToolTipText("press to list all the online WORTH users");
        listOnlineUsersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listOnlineUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOnlineUsersButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel1.setText("Create a new WORTH project:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setText("Show a WORTH project menu:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel3.setText("Do you want to list something?");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel4.setText("Others:");

        newMembershipsButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        newMembershipsButton.setText(" Check for New Memberships");
        newMembershipsButton.setToolTipText("press to check if other WORTH users added you as a member of some projects");
        newMembershipsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newMembershipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMembershipsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(newProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showProjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(newProjectButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(showProjectButton)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(introLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listProjectsButton)
                                .addGap(54, 54, 54)
                                .addComponent(listAllUsersButton)
                                .addGap(54, 54, 54)
                                .addComponent(listOnlineUsersButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(newMembershipsButton)
                                .addGap(54, 54, 54)
                                .addComponent(profileButton)
                                .addGap(54, 54, 54)
                                .addComponent(logoutButton)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(introLabel)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showProjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listProjectsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listAllUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listOnlineUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMembershipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.operation = 0;
        this.dispose();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void newProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectButtonActionPerformed
        this.operation = 1;
        this.newProjName = this.newProjectName.getText();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_newProjectButtonActionPerformed

    private void showProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProjectButtonActionPerformed
        this.operation = 2;
        this.showProjectName = this.showProjectLabel.getText();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_showProjectButtonActionPerformed

    private void listProjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProjectsButtonActionPerformed
        this.operation = 3;
        this.waitUser.setUserDone();
    }//GEN-LAST:event_listProjectsButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        this.operation = 4;
        this.dispose();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_profileButtonActionPerformed

    private void listAllUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllUsersButtonActionPerformed
        this.operation = 5;
        this.waitUser.setUserDone();
    }//GEN-LAST:event_listAllUsersButtonActionPerformed

    private void listOnlineUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOnlineUsersButtonActionPerformed
        this.operation = 6;
        this.waitUser.setUserDone();
    }//GEN-LAST:event_listOnlineUsersButtonActionPerformed

    private void newMembershipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMembershipsButtonActionPerformed
        this.operation = 7;
        this.waitUser.setUserDone();
    }//GEN-LAST:event_newMembershipsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton listAllUsersButton;
    private javax.swing.JButton listOnlineUsersButton;
    private javax.swing.JButton listProjectsButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton newMembershipsButton;
    private javax.swing.JButton newProjectButton;
    private javax.swing.JTextField newProjectName;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton showProjectButton;
    private javax.swing.JTextField showProjectLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
