import java.io.File;
import javax.swing.ImageIcon;

public class ProjectMenu extends javax.swing.JFrame {

    private waitUserAction waitUser;
    private static final long serialVersionUID = 5L;
    private String name;
    private String user;
    public int operation;
    public String newCardName;
    public String newCardDescription;
    public String cardToShow;
    public String destinationList;
    public String cardToMove;
    public String historyWantedCard;
    public String cardToDelete;
    
    public ProjectMenu(String prjName, waitUserAction wait, String user){
        this.name = prjName;
        this.waitUser = wait;
        this.user = user;
        initComponents();
    }
    
    public ProjectMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prNameLabel = new javax.swing.JLabel();
        prNameLabel.setText("This is the "+"'"+this.name+"'"+" project menu.");
        jLabel1 = new javax.swing.JLabel();
        newCardTextField = new javax.swing.JTextField();
        newCardButton = new javax.swing.JButton();
        this.newCardButton.setIcon(new ImageIcon("icone"+File.separator+"addcard.png"));
        jLabel2 = new javax.swing.JLabel();
        showCardTextField = new javax.swing.JTextField();
        showCardButton = new javax.swing.JButton();
        this.showCardButton.setIcon(new ImageIcon("icone"+File.separator+"card.png"));
        jLabel3 = new javax.swing.JLabel();
        listComboBox = new javax.swing.JComboBox<>();
        moveCardButton = new javax.swing.JButton();
        this.moveCardButton.setIcon(new ImageIcon("icone"+File.separator+"move.png"));
        jLabel4 = new javax.swing.JLabel();
        moveCardTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chatButton = new javax.swing.JButton();
        this.chatButton.setIcon(new ImageIcon("icone"+File.separator+"chat.png"));
        deleteProjectButton = new javax.swing.JButton();
        this.deleteProjectButton.setIcon(new ImageIcon("icone"+File.separator+"deleteproject.png"));
        backToHomePageButton = new javax.swing.JButton();
        this.backToHomePageButton.setIcon(new ImageIcon("icone"+File.separator+"back.png"));
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        historyCardTextField = new javax.swing.JTextField();
        historyButton = new javax.swing.JButton();
        this.historyButton.setIcon(new ImageIcon("icone"+File.separator+"history.png"));
        listCardsButton = new javax.swing.JButton();
        this.listCardsButton.setIcon(new ImageIcon("icone"+File.separator+"cardlist.png"));
        jLabel11 = new javax.swing.JLabel();
        deleteCardTextField = new javax.swing.JTextField();
        deleteCardButton = new javax.swing.JButton();
        this.deleteCardButton.setIcon(new ImageIcon("icone"+File.separator+"deletecard.png"));
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        this.jLabel10.setText(this.user+", ONLINE");
        kanbanButton = new javax.swing.JButton();
        this.kanbanButton.setIcon(new ImageIcon("icone"+File.separator+"kanban.png"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WORTH Project Menu");

        prNameLabel.setFont(new java.awt.Font("Ubuntu", 3, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel1.setText("3. Insert a new card for a new project activity:");

        newCardTextField.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        newCardTextField.setToolTipText("enter the card name");

        newCardButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        newCardButton.setText(" Add New Card");
        newCardButton.setToolTipText("press to create a card for this project");
        newCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCardButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setText("1. Show a card details:");

        showCardTextField.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        showCardTextField.setToolTipText("enter the card name");

        showCardButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        showCardButton.setText(" Show Card");
        showCardButton.setToolTipText("press to show all the details of the specified card");
        showCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCardButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel3.setText("2. Move card from its current list to destination:");

        listComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In progress list", "To be revised list", "Done list" }));
        listComboBox.setToolTipText("choose the destination list for this card");
        listComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        moveCardButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        moveCardButton.setText(" Move Card");
        moveCardButton.setToolTipText("press to move the specified card to the chosen list");
        moveCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moveCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveCardButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel4.setText("Here are some operation you can do with it.");

        moveCardTextField.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        moveCardTextField.setToolTipText("enter the card name");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 17)); // NOI18N
        jLabel5.setText(">> WORTH System <<");

        chatButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        chatButton.setText(" Chat and Members");
        chatButton.setToolTipText("show the project chat and members");
        chatButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatButtonActionPerformed(evt);
            }
        });

        deleteProjectButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        deleteProjectButton.setText(" Delete this project");
        deleteProjectButton.setToolTipText("press to delete this project (allowed only when all the cards are in the done list)");
        deleteProjectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProjectButtonActionPerformed(evt);
            }
        });

        backToHomePageButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        backToHomePageButton.setText("   Back to Home Page");
        backToHomePageButton.setToolTipText("press to get back to the WORTH home page");
        backToHomePageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToHomePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomePageButtonActionPerformed(evt);
            }
        });

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setToolTipText("enter the new card description");
        jScrollPane1.setViewportView(descriptionTextArea);

        jLabel6.setText("type the new card name");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel8.setText("6. Others:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel9.setText("4. Show the history of the card:");

        historyCardTextField.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        historyCardTextField.setToolTipText("enter the name of the card you want to see the history");

        historyButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        historyButton.setText(" Get Card History");
        historyButton.setToolTipText("press to see the card history");
        historyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        listCardsButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        listCardsButton.setText(" List all Cards of this project");
        listCardsButton.setToolTipText("press to see the list of all the cards of this project");
        listCardsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCardsButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel11.setText("5. Delete a card in this project:");

        deleteCardTextField.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        deleteCardTextField.setToolTipText("enter the name of the card you want to delete");

        deleteCardButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        deleteCardButton.setText(" Delete Card");
        deleteCardButton.setToolTipText("press to delete the specified card from this project");
        deleteCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCardButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("type the new card description (max 1000 characters)");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        kanbanButton.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        kanbanButton.setText(" Request project Kanban");
        kanbanButton.setToolTipText("press to open the project kanban window");
        kanbanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kanbanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kanbanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(backToHomePageButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kanbanButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(listCardsButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11))
                                        .addGap(125, 125, 125)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(historyCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deleteCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(34, 34, 34)
                                        .addComponent(newCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(moveCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(showCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(chatButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteProjectButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deleteCardButton)
                                            .addComponent(historyButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(showCardButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(listComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(moveCardButton)
                                            .addComponent(newCardButton)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(prNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(showCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(92, 92, 92)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(listComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(newCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(newCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(historyCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(deleteCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kanbanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listCardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(backToHomePageButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToHomePageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomePageButtonActionPerformed
        this.operation = 0;
        this.dispose();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_backToHomePageButtonActionPerformed

    private void newCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCardButtonActionPerformed
        this.operation = 1;
        this.newCardName = this.newCardTextField.getText();
        this.newCardDescription = this.descriptionTextArea.getText();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_newCardButtonActionPerformed

    private void showCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCardButtonActionPerformed
        this.cardToShow = this.showCardTextField.getText();
        this.operation = 2;
        this.waitUser.setUserDone();
    }//GEN-LAST:event_showCardButtonActionPerformed

    private void listCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCardsButtonActionPerformed
        this.operation = 3;
        this.waitUser.setUserDone();
    }//GEN-LAST:event_listCardsButtonActionPerformed

    private void moveCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveCardButtonActionPerformed
        this.operation = 4;
        this.destinationList = (String) this.listComboBox.getSelectedItem();
        this.cardToMove = this.moveCardTextField.getText();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_moveCardButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        this.operation = 5;
        this.historyWantedCard = this.historyCardTextField.getText();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_historyButtonActionPerformed

    private void deleteProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProjectButtonActionPerformed
        this.operation = 6;
        this.dispose();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_deleteProjectButtonActionPerformed

    private void deleteCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCardButtonActionPerformed
        this.operation = 7;
        this.cardToDelete = this.deleteCardTextField.getText();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_deleteCardButtonActionPerformed

    private void chatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatButtonActionPerformed
        this.operation = 8;
        this.dispose();
        this.waitUser.setUserDone();
    }//GEN-LAST:event_chatButtonActionPerformed

    private void kanbanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kanbanButtonActionPerformed
        this.operation = 9;
        this.waitUser.setUserDone();
    }//GEN-LAST:event_kanbanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHomePageButton;
    private javax.swing.JButton chatButton;
    private javax.swing.JButton deleteCardButton;
    private javax.swing.JTextField deleteCardTextField;
    private javax.swing.JButton deleteProjectButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton historyButton;
    private javax.swing.JTextField historyCardTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kanbanButton;
    private javax.swing.JButton listCardsButton;
    private javax.swing.JComboBox<String> listComboBox;
    private javax.swing.JButton moveCardButton;
    private javax.swing.JTextField moveCardTextField;
    private javax.swing.JButton newCardButton;
    private javax.swing.JTextField newCardTextField;
    private javax.swing.JLabel prNameLabel;
    private javax.swing.JButton showCardButton;
    private javax.swing.JTextField showCardTextField;
    // End of variables declaration//GEN-END:variables
}
